In [1]:
# Système
import os
import sys
import time

# Built-in imports
import warnings
from collections import Counter
import pickle

# Data manipulation
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff
from plotly.subplots import make_subplots
import missingno

# Sklearn imports
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    GridSearchCV
)
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    mean_squared_error,
    r2_score,
    root_mean_squared_error,
    mean_absolute_error
)

# ML Models - Linear
from sklearn.linear_model import (
    LogisticRegression,
    Perceptron,
    SGDClassifier,
    Lasso,
    LassoCV
)


from sklearn.preprocessing import LabelEncoder

# ML Models - SVM
from sklearn.svm import SVC, LinearSVC

# ML Models - Ensemble
from sklearn.ensemble import RandomForestClassifier

# ML Models - Other
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier

# Disable warnings
warnings.filterwarnings('ignore')

In [2]:
from google.colab import drive
drive.mount("/content/drive/", force_remount=True)

Mounted at /content/drive/

# MPI TRAIN AND STORE THE BEST MODEL

In [3]:
doc1_df_train = pd.read_csv("/content/drive/MyDrive/Memoire/DIORES/Datasets/V2/L1MPI/doc1/doc1_df_train.csv");
doc2_df_train = pd.read_csv("/content/drive/MyDrive/Memoire/DIORES/Datasets/V2/L1MPI/doc2/doc2_df_train.csv");
doc3_df_train = pd.read_csv("/content/drive/MyDrive/Memoire/DIORES/Datasets/V2/L1MPI/doc3/doc3_df_train.csv");

In [4]:
doc1_df_train

,REGION_DE_NAISSANCE,CREDIT,NIVEAU,SESSION,MENTION,MOYENNE ANNUELLE,RESULTAT,RESULTAT APP EVALUATION,Année BAC,Sexe,...,RESULTAT_Encode,SESSION_Encode,MENTION_Encode,Academie perf.,Residence perf.,Résidence_Encode,Ets. de provenance_Encode,Centre d'Ec._Encode,Académie de l'Ets. Prov._Encode,REGION_DE_NAISSANCE_Encode
0,Dakar,60,1,Première Session,Passable,11.61,PASSE,1,2018,M,...,2,1,0,10.668400,10.627500,70,95,72,10,0
1,Thiès,15,1,Deuxième Session,NaN,3.34,NON ADMIS,1,2018,M,...,0,0,4,10.926122,11.295625,76,33,18,14,9
2,Dakar,60,1,Première Session,Assez-Bien,13.43,PASSE,1,2018,M,...,2,1,1,10.693385,10.722727,42,75,54,9,0
3,Kaolack,43,1,Deuxième Session,NaN,8.90,AUTORISE,1,2018,M,...,1,0,4,10.863333,11.245000,29,139,12,4,3
4,Tambacounda,45,1,Deuxième Session,NaN,7.89,AUTORISE,1,2018,M,...,1,0,4,11.000000,11.202000,73,123,89,13,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,Dakar,20,1,Deuxième Session,NaN,4.83,NON ADMIS,1,2018,M,...,0,0,4,10.693385,10.695217,60,100,10,9,0
274,Dakar,60,1,Deuxième Session,Passable,10.24,PASSE,1,2018,F,...,2,0,0,11.080526,10.754516,7,138,104,0,0
275,0,52,1,Deuxième Session,NaN,10.06,AUTORISE,1,2018,M,...,1,0,4,11.080526,12.524286,57,131,95,0,11
276,Louga,60,1,Première Session,Passable,10.21,PASSE,1,2018,M,...,2,1,0,10.847500,10.840000,30,120,87,7,5
277,Louga,60,1,Première Session,Assez-Bien,12.94,PASSE,1,2018,M,...,2,1,1,10.847500,10.815000,39,145,88,7,5

In [5]:
doc1_df_train.dtypes

REGION_DE_NAISSANCE                 object
CREDIT                               int64
NIVEAU                               int64
SESSION                             object
MENTION                             object
MOYENNE ANNUELLE                   float64
RESULTAT                            object
RESULTAT APP EVALUATION              int64
Année BAC                            int64
Sexe                                object
Série                               object
Ets. de provenance                  object
Type candidature                    object
Académie de l'Ets. Prov.            object
Résidence                           object
Centre d'Ec.                        object
Nbre Fois au BAC                     int64
Mention                             object
Résultat                            object
Groupe Résultat                      int64
Année de l'Extrait EC                int64
Moy. nde                           float64
Moy. ère                           float64
Moy. S Term.                       float64
Moy. S Term..1                     float64
MATH                                 int64
SCPH                                 int64
FR                                   int64
PHILO                                int64
AN                                   int64
SVT                                float64
COME                               float64
AFTA                               float64
EPAT                               float64
Tot. Pts au Grp.                     int64
Moyenne au Grp.                    float64
Moy. Gle                           float64
Moy. sur Mat.Fond.                 float64
Age en Décembre 2018                 int64
Score DAP                          float64
Rang DAP                             int64
Score L1                           float64
Rang L1                              int64
S1                                   int64
S2                                   int64
S3                                   int64
Homme                                int64
Femme                                int64
Série_Encode                         int64
Sexe_Encode                          int64
RESULTAT_Encode                      int64
SESSION_Encode                       int64
MENTION_Encode                       int64
Academie perf.                     float64
Residence perf.                    float64
Résidence_Encode                     int64
Ets. de provenance_Encode            int64
Centre d'Ec._Encode                  int64
Académie de l'Ets. Prov._Encode      int64
REGION_DE_NAISSANCE_Encode           int64
dtype: object

In [6]:
columns = ["MATH", "SCPH", "SVT", "FR", "PHILO", "AN", "Moy. Gle",
           "Moy. sur Mat.Fond.", "Age en Décembre 2018", "S1", "S2",
           "Academie perf.", "Residence perf."]

from itertools import combinations

fixedSize = 6

# Obtenir uniquement les combinaisons de taille fixedSize
res = list(combinations(columns, fixedSize))

print(f"Nombre de combinaisons de {fixedSize} éléments : {len(res)}")

Nombre de combinaisons de 6 éléments : 1716

In [7]:
from math import sqrt
import pandas as pd

def compute_distance_errors(df, col1, col2):
    """
    Calcule les erreurs MAE et RMSE entre deux colonnes d'un DataFrame,
    ajoute les colonnes correspondantes et renvoie les moyennes des erreurs.

    Args:
        df (pd.DataFrame): Le DataFrame contenant les colonnes.
        col1 (str): Le nom de la première colonne.
        col2 (str): Le nom de la seconde colonne.

    Returns:
        tuple: (mae_distance_error, rmse_distance_error)
    """
    # Calcul des erreurs élémentaires
    df['mae_distance_error'] = abs(df[col1] - df[col2])
    df['rmse_distance_error'] = (df[col1] - df[col2])**2

    # Moyennes des erreurs
    mae_distance_error = df['mae_distance_error'].mean()
    rmse_distance_error = sqrt(df['rmse_distance_error'].mean())

    # Retour des erreurs
    return mae_distance_error, rmse_distance_error

In [8]:
def root_mean_squared_error(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

In [9]:
def adjust_predictions(y_pred, y_true):
   """
   Ajuste les prédictions pour les maintenir dans les limites réalistes des données observées
   et arrondit les résultats.

   Args:
       y_pred (array-like): Les prédictions brutes du modèle
       y_true (array-like): Les vraies valeurs observées

   Returns:
       array-like: Les prédictions ajustées

   Example:
       >>> y_true = [12, 15, 8, 17, 10]
       >>> y_pred = [13.456, 22.789, -3.123, 16.789, 9.234]
       >>> adjusted = adjust_predictions(y_pred, y_true)
       >>> print(adjusted)
       [13.46, 17.00, 8.00, 16.79, 9.23]
   """
   min_score = min(y_true)
   max_score = max(y_true)
   y_pred = np.clip(y_pred, min_score, max_score)
   y_pred = np.round(y_pred, decimals=2)
   return y_pred

In [10]:
def calculate_mrr(y_true, y_pred):
    """
    Calcule le Mean Reciprocal Rank (MRR).

    Args:
        y_true (pd.Series): Valeurs réelles (avec des indices correspondant à y_pred).
        y_pred (np.ndarray): Prédictions associées aux valeurs réelles.

    Returns:
        float: MRR calculé.
    """
    sorted_indices = np.argsort(-y_pred)  # Indices triés par prédictions descendantes
    ranks = np.argsort(sorted_indices) + 1  # Rangs associés aux prédictions
    reciprocal_ranks = 1 / ranks[y_true.index]
    return sum(reciprocal_ranks)

In [11]:
def train_lasso_models(train_dfs, res, names=['Doc1', 'Doc2', 'Doc3'], target_col='Score L1', alpha=0.01):
    """
    Entraîne les modèles Lasso sur les données d'entraînement avec validation.

    Args:
        train_dfs (list): Liste des DataFrames d'entraînement.
        res (list): Liste des combinaisons de features à tester.
        names (list): Noms des documents/modèles.
        target_col (str): Nom de la colonne cible.
        alpha (float): Paramètre de régularisation Lasso.

    Returns:
        dict: Dictionnaire contenant les meilleurs modèles pour chaque document.
    """
    best_models = {}
    # val_best_rmse = None
    # val_best_mae = None

    for train_df, name in zip(train_dfs, names):
        print(f"\nEntraînement pour {name}")
        print("=" * 50)

        validation_results = []
        train_data, val_data = train_test_split(train_df, test_size=0.2, random_state=42)

        for feature_cols in res:
            # Préparation des données
            X_train = train_data[list(feature_cols)]
            y_train = train_data[target_col]
            X_val = val_data[list(feature_cols)]
            y_val = val_data[target_col]

            # Standardisation
            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train)
            X_val_scaled = scaler.transform(X_val)

            # Entraînement
            lasso = Lasso(alpha=alpha, positive=True)
            lasso.fit(X_train_scaled, y_train)

            # Prédictions et métriques
            y_val_pred = lasso.predict(X_val_scaled)
            val_rmse = ((y_val - y_val_pred) ** 2).mean() ** 0.5
            val_mae = abs(y_val - y_val_pred).mean()

            # val_best_rmse = val_rmse
            # val_best_mae = val_mae

            validation_results.append({
                'features': feature_cols,
                'model': lasso,
                'scaler': scaler,
                'coefs': lasso.coef_.ravel(),
                'val_rmse': val_rmse,
                'val_mae': val_mae
            })

            # print(f"Validation RMSE: {val_rmse:.4f}, MAE: {val_mae:.4f}")


            # Afficher les coefficients LASSO
            feature_cols_selected = feature_cols[:len(lasso.coef_)]
            lasso_coefficients_df = pd.DataFrame({'Feature': feature_cols_selected, 'Coefficient': lasso.coef_.ravel()})
            lasso_coefficients_df = lasso_coefficients_df.sort_values(by='Coefficient', ascending=False)
            print("Coefficients LASSO :\n", lasso_coefficients_df)
            print("RMSE :", val_rmse)
            print("MAE :", val_mae, "\n", ("_"*30))


        # Sélection du meilleur modèle
        best_val_model = min(validation_results, key=lambda x: x['val_rmse'])
        best_models[name] = best_val_model

    return best_models

In [12]:
def save_models(final_results, base_path='models'):
    """
    Sauvegarde les modèles et leurs résultats.

    Args:
        final_results (dict): Résultats finaux contenant les modèles.
        base_path (str): Chemin de base pour la sauvegarde.
    """
    os.makedirs(base_path, exist_ok=True)

    for name, results in final_results.items():
        model_path = os.path.join(base_path, name)
        os.makedirs(model_path, exist_ok=True)

        # Sauvegarder le modèle
        with open(os.path.join(model_path,'lasso_globale_model.pkl'), 'wb') as f:
            pickle.dump(results['model'], f)

        # Sauvegarder le scaler
        with open(os.path.join(model_path, 'lasso_globale_scaler.pkl'), 'wb') as f:
            pickle.dump(results['scaler'], f)

        # Sauvegarder les autres informations
        info = {
            'val_rmse': results['val_rmse'],
            'val_mae': results['val_mae'],
            'features': results['features']
        }
        with open(os.path.join(model_path, 'lasso_globale_info.pkl'), 'wb') as f:
            pickle.dump(info, f)

        print(f"Modèle {name} sauvegardé dans {model_path}")

In [13]:
# Préparer les données
train_dfs = [doc1_df_train, doc2_df_train, doc3_df_train]
names = ['Doc1', 'Doc2', 'Doc3']

# Entraîner les modèles
best_models = train_lasso_models(
    train_dfs=train_dfs,  # Liste des DataFrames d'entraînement
    res=res,             # Combinaisons de features à tester
    names=names,         # Noms des documents
    target_col='Score L1', # Variable cible
    alpha=0.01           # Paramètre de régularisation
)


# Sauvegarder les modèles
save_models(
    final_results=best_models,
    base_path='models'  # Dossier de sauvegarde
)

# print("Best Model : ", best_models)


# Reformater les données
data = []
for doc, values in best_models.items():
    data.append({
        'Document': doc,
        'Features': ', '.join(values['features']),
        # 'Modèle': str(values['model']),
        # 'Scaler': str(values['scaler']),
        'coefs': [round(float(c), 2) for c in values['coefs']],
        'RMSE Validation': round(float(values['val_rmse']), 2),
        'MAE Validation': round(float(values['val_mae']), 2)
    })

# Créer un DataFrame
df_best_models = pd.DataFrame(data)

# Afficher joliment
print(df_best_models.to_string(index=False))

Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
               Feature  Coefficient
3                  AN    13.238239
4  Moy. sur Mat.Fond.    11.165999
2               PHILO     8.864715
0                 SVT     2.209193
1                  FR     1.466122
5                  S2     0.000000
RMSE : 42.01828490541567
MAE : 36.82078627944441
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
3                  AN    13.233608
4  Moy. sur Mat.Fond.    11.135414
2               PHILO     8.859768
0                 SVT     2.208416
1                  FR     1.451881
5      Academie perf.     0.109656
RMSE : 42.032276642193146
MAE : 36.8506972079422
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
3                  AN    13.238239
4  Moy. sur Mat.Fond.    11.165999
2               PHILO     8.864715
0                 SVT     2.209193
1                  FR     1.466122
5     Residence perf.     0.000000
RMSE : 42.01828490541567
MAE : 36.82078627944441
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5                    S1    24.566525
2                 PHILO     6.504325
3                    AN     2.719999
0                   SVT     0.534539
1                    FR     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 39.36713098606963
MAE : 29.770364067595388
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
3                    AN    11.762091
2                 PHILO     7.707712
0                   SVT     3.099166
1                    FR     0.202775
4  Age en Décembre 2018     0.000000
5                    S2     0.000000
RMSE : 41.91614128692188
MAE : 36.97809682140254
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
3                    AN    11.716503
2                 PHILO     7.647848
5        Academie perf.     3.044771
0                   SVT     3.009157
1                    FR     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 42.39062626355962
MAE : 37.80747997918676
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
3                    AN    11.749615
2                 PHILO     7.593435
0                   SVT     2.955964
5       Residence perf.     1.719387
1                    FR     0.075019
4  Age en Décembre 2018     0.000000
RMSE : 41.70392878670769
MAE : 36.795718227992985
 ______________________________
Coefficients LASSO :
   Feature  Coefficient
4      S1    33.258901
5      S2     8.833117
2   PHILO     6.773619
3      AN     2.555037
1      FR     0.000000
0     SVT     0.000000
RMSE : 39.50146207075644
MAE : 30.07423857700368
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
4              S1    24.689925
2           PHILO     6.402352
5  Academie perf.     3.726421
3              AN     2.542911
0             SVT     0.407811
1              FR     0.000000
RMSE : 40.10882390596652
MAE : 30.67749108102527
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
4               S1    25.158533
2            PHILO     6.144686
5  Residence perf.     4.511024
3               AN     2.365780
0              SVT     0.091971
1               FR     0.000000
RMSE : 39.07333889793411
MAE : 29.071981596280107
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
3              AN    11.716503
2           PHILO     7.647848
5  Academie perf.     3.044771
0             SVT     3.009157
1              FR     0.000000
4              S2     0.000000
RMSE : 42.39062626355962
MAE : 37.80747997918676
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
3               AN    11.749615
2            PHILO     7.593435
0              SVT     2.955964
5  Residence perf.     1.719387
1               FR     0.075019
4               S2     0.000000
RMSE : 41.70392878670769
MAE : 36.795718227992985
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
3               AN    11.712278
2            PHILO     7.628165
0              SVT     2.986607
4   Academie perf.     2.890055
5  Residence perf.     0.323399
1               FR     0.000000
RMSE : 42.32830391762573
MAE : 37.730301147252064
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                 PHILO    11.320251
4    Moy. sur Mat.Fond.     9.612830
1                    FR     5.081674
0                   SVT     3.419799
3              Moy. Gle     0.000000
5  Age en Décembre 2018     0.000000
RMSE : 42.77825797729266
MAE : 38.72623005931262
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
5                  S1    26.774765
4  Moy. sur Mat.Fond.    11.690145
2               PHILO     8.670711
0                 SVT     0.000000
1                  FR     0.000000
3            Moy. Gle     0.000000
RMSE : 39.90637830801226
MAE : 30.400030601556086
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
2               PHILO    11.320251
4  Moy. sur Mat.Fond.     9.612830
1                  FR     5.081674
0                 SVT     3.419799
3            Moy. Gle     0.000000
5                  S2     0.000000
RMSE : 42.77825797729266
MAE : 38.72623005931262
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
2               PHILO    11.287341
4  Moy. sur Mat.Fond.     9.444435
1                  FR     4.994699
0                 SVT     3.413239
5      Academie perf.     0.614628
3            Moy. Gle     0.000000
RMSE : 42.89456439802417
MAE : 38.87775017662521
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
2               PHILO    11.320251
4  Moy. sur Mat.Fond.     9.612830
1                  FR     5.081674
0                 SVT     3.419799
3            Moy. Gle     0.000000
5     Residence perf.     0.000000
RMSE : 42.77825797729266
MAE : 38.72623005931262
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5                    S1    26.110276
3              Moy. Gle    10.077113
2                 PHILO     5.248787
0                   SVT     0.000000
1                    FR     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 40.17289591396221
MAE : 29.84760366738443
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                 PHILO     8.916594
3              Moy. Gle     8.047664
0                   SVT     2.992554
1                    FR     2.557696
4  Age en Décembre 2018     0.000000
5                    S2     0.000000
RMSE : 42.91922209011926
MAE : 38.84067627789115
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                 PHILO     8.935297
3              Moy. Gle     7.839898
0                   SVT     3.002369
1                    FR     2.523319
5        Academie perf.     0.618666
4  Age en Décembre 2018     0.000000
RMSE : 43.020896147629614
MAE : 39.00009893721369
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                 PHILO     8.916594
3              Moy. Gle     8.047664
0                   SVT     2.992554
1                    FR     2.557696
4  Age en Décembre 2018     0.000000
5       Residence perf.     0.000000
RMSE : 42.91922209011926
MAE : 38.84067627789115
 ______________________________
Coefficients LASSO :
     Feature  Coefficient
4        S1    37.280510
5        S2    11.526534
3  Moy. Gle    10.194116
2     PHILO     5.510312
1        FR     0.000000
0       SVT     0.000000
RMSE : 40.33263226679958
MAE : 30.13953586177033
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
4              S1    26.107301
3        Moy. Gle     9.881866
2           PHILO     5.262316
5  Academie perf.     0.571574
1              FR     0.000000
0             SVT     0.000000
RMSE : 40.252095444088596
MAE : 29.984806627416162
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
4               S1    26.110276
3         Moy. Gle    10.077113
2            PHILO     5.248787
0              SVT     0.000000
1               FR     0.000000
5  Residence perf.     0.000000
RMSE : 40.17289591396221
MAE : 29.84760366738443
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
2           PHILO     8.935297
3        Moy. Gle     7.839898
0             SVT     3.002369
1              FR     2.523319
5  Academie perf.     0.618666
4              S2     0.000000
RMSE : 43.020896147629614
MAE : 39.00009893721369
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
2            PHILO     8.916594
3         Moy. Gle     8.047664
0              SVT     2.992554
1               FR     2.557696
4               S2     0.000000
5  Residence perf.     0.000000
RMSE : 42.91922209011926
MAE : 38.84067627789115
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
2            PHILO     8.935297
3         Moy. Gle     7.839898
0              SVT     3.002369
1               FR     2.523319
4   Academie perf.     0.618666
5  Residence perf.     0.000000
RMSE : 43.020896147629614
MAE : 39.00009893721369
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5                    S1    26.774773
3    Moy. sur Mat.Fond.    11.690169
2                 PHILO     8.670675
0                   SVT     0.000000
1                    FR     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 39.906371720484266
MAE : 30.400028874618005
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                 PHILO    11.320294
3    Moy. sur Mat.Fond.     9.612834
1                    FR     5.081637
0                   SVT     3.419732
4  Age en Décembre 2018     0.000000
5                    S2     0.000000
RMSE : 42.77826862624707
MAE : 38.726240482802005
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                 PHILO    11.287394
3    Moy. sur Mat.Fond.     9.444438
1                    FR     4.994608
0                   SVT     3.413202
5        Academie perf.     0.614636
4  Age en Décembre 2018     0.000000
RMSE : 42.89457510432933
MAE : 38.87775906375186
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                 PHILO    11.320294
3    Moy. sur Mat.Fond.     9.612834
1                    FR     5.081637
0                   SVT     3.419732
4  Age en Décembre 2018     0.000000
5       Residence perf.     0.000000
RMSE : 42.77826862624707
MAE : 38.726240482802005
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4                  S1    36.413722
3  Moy. sur Mat.Fond.    11.703265
5                  S2     9.950036
2               PHILO     8.916505
1                  FR     0.000000
0                 SVT     0.000000
RMSE : 40.03784076683507
MAE : 30.63640816943708
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4                  S1    26.760591
3  Moy. sur Mat.Fond.    11.430910
2               PHILO     8.596413
5      Academie perf.     1.015982
1                  FR     0.000000
0                 SVT     0.000000
RMSE : 40.07355096717249
MAE : 30.642286206704007
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4                  S1    26.774773
3  Moy. sur Mat.Fond.    11.690169
2               PHILO     8.670675
0                 SVT     0.000000
1                  FR     0.000000
5     Residence perf.     0.000000
RMSE : 39.906371720484266
MAE : 30.400028874618005
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
2               PHILO    11.287394
3  Moy. sur Mat.Fond.     9.444438
1                  FR     4.994608
0                 SVT     3.413202
5      Academie perf.     0.614636
4                  S2     0.000000
RMSE : 42.89457510432933
MAE : 38.87775906375186
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
2               PHILO    11.320294
3  Moy. sur Mat.Fond.     9.612834
1                  FR     5.081637
0                 SVT     3.419732
4                  S2     0.000000
5     Residence perf.     0.000000
RMSE : 42.77826862624707
MAE : 38.726240482802005
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
2               PHILO    11.287394
3  Moy. sur Mat.Fond.     9.444438
1                  FR     4.994608
0                 SVT     3.413202
4      Academie perf.     0.614636
5     Residence perf.     0.000000
RMSE : 42.89457510432933
MAE : 38.87775906375186
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
4                    S1    35.004525
5                    S2     9.673024
2                 PHILO     7.304995
0                   SVT     0.000000
1                    FR     0.000000
3  Age en Décembre 2018     0.000000
RMSE : 39.83474852017592
MAE : 30.229225057320594
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
4                    S1    25.602385
2                 PHILO     6.902967
5        Academie perf.     3.823720
0                   SVT     0.521338
1                    FR     0.000000
3  Age en Décembre 2018     0.000000
RMSE : 40.47730983876545
MAE : 30.83995936013112
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
4                    S1    26.021728
2                 PHILO     6.599189
5       Residence perf.     4.663999
0                   SVT     0.185337
1                    FR     0.000000
3  Age en Décembre 2018     0.000000
RMSE : 39.36518364950285
MAE : 29.177490915519943
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                 PHILO    10.013602
0                   SVT     3.988373
1                    FR     3.313512
5        Academie perf.     3.105696
3  Age en Décembre 2018     0.000000
4                    S2     0.000000
RMSE : 43.4593774977149
MAE : 39.37505261381312
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                 PHILO     9.947237
0                   SVT     3.929678
1                    FR     3.487358
5       Residence perf.     1.792483
3  Age en Décembre 2018     0.000000
4                    S2     0.000000
RMSE : 42.59933316418058
MAE : 38.350971351723466
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                 PHILO     9.990478
0                   SVT     3.961215
1                    FR     3.302297
4        Academie perf.     2.920397
5       Residence perf.     0.389009
3  Age en Décembre 2018     0.000000
RMSE : 43.37468089584724
MAE : 39.28496978265014
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
3              S1    36.652816
4              S2    11.328606
2           PHILO     7.189725
5  Academie perf.     4.090282
1              FR     0.000000
0             SVT     0.000000
RMSE : 40.709500236343686
MAE : 31.25700709500327
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
3               S1    36.490949
4               S2    10.767145
2            PHILO     6.854765
5  Residence perf.     4.816839
1               FR     0.000000
0              SVT     0.000000
RMSE : 39.50123293279675
MAE : 29.466647844418812
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
3               S1    25.950318
2            PHILO     6.619516
5  Residence perf.     3.646587
4   Academie perf.     2.081516
0              SVT     0.213513
1               FR     0.000000
RMSE : 39.878904778048515
MAE : 29.81817229634805
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
2            PHILO     9.990478
0              SVT     3.961215
1               FR     3.302297
4   Academie perf.     2.920397
5  Residence perf.     0.389009
3               S2     0.000000
RMSE : 43.37468089584724
MAE : 39.28496978265014
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                    AN    15.052187
4    Moy. sur Mat.Fond.    10.266731
0                   SVT     2.531507
1                    FR     2.195184
3              Moy. Gle     0.000000
5  Age en Décembre 2018     0.000000
RMSE : 41.36414386132849
MAE : 37.50964820576779
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
5                  S1    25.748623
4  Moy. sur Mat.Fond.     8.601265
2                  AN     5.134225
3            Moy. Gle     3.166605
1                  FR     0.000000
0                 SVT     0.000000
RMSE : 38.59931730569339
MAE : 30.115045426561455
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
2                  AN    15.052187
4  Moy. sur Mat.Fond.    10.266731
0                 SVT     2.531507
1                  FR     2.195184
3            Moy. Gle     0.000000
5                  S2     0.000000
RMSE : 41.36414386132849
MAE : 37.50964820576779
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
2                  AN    15.025767
4  Moy. sur Mat.Fond.    10.125694
0                 SVT     2.527111
1                  FR     2.126358
5      Academie perf.     0.514428
3            Moy. Gle     0.000000
RMSE : 41.4360929180452
MAE : 37.64814837037518
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
2                  AN    15.052187
4  Moy. sur Mat.Fond.    10.266731
0                 SVT     2.531507
1                  FR     2.195184
3            Moy. Gle     0.000000
5     Residence perf.     0.000000
RMSE : 41.36414386132849
MAE : 37.50964820576779
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5                    S1    25.965427
3              Moy. Gle    10.649509
2                    AN     2.392530
0                   SVT     0.000000
1                    FR     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 39.35678974300387
MAE : 29.980267235925787
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                    AN    12.722801
3              Moy. Gle     8.352506
0                   SVT     2.193582
1                    FR     0.000000
4  Age en Décembre 2018     0.000000
5                    S2     0.000000
RMSE : 41.98860456632035
MAE : 37.774868903474975
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                    AN    12.723174
3              Moy. Gle     8.164641
0                   SVT     2.201976
5        Academie perf.     0.553108
1                    FR     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 42.040731458289855
MAE : 37.91646327253583
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                    AN    12.722801
3              Moy. Gle     8.352506
0                   SVT     2.193582
1                    FR     0.000000
4  Age en Décembre 2018     0.000000
5       Residence perf.     0.000000
RMSE : 41.98860456632035
MAE : 37.774868903474975
 ______________________________
Coefficients LASSO :
     Feature  Coefficient
4        S1    34.524078
3  Moy. Gle    10.796836
5        S2     8.734561
2        AN     2.232496
1        FR     0.000000
0       SVT     0.000000
RMSE : 39.45896197517041

In [14]:
df_best_models

,Document,Features,coefs,RMSE Validation,MAE Validation
0,Doc1,"MATH, FR, PHILO, Age en Décembre 2018, S1, S2","[13.38, 0.0, 5.46, 0.0, 28.7, 0.0]",36.86,27.66
1,Doc2,"MATH, SCPH, SVT, PHILO, Moy. Gle, S1","[9.1, 9.06, 0.0, 3.61, 2.72, 26.36]",40.46,32.38
2,Doc3,"MATH, SCPH, FR, AN, Moy. sur Mat.Fond., S1","[12.72, 6.59, 0.0, 4.02, 1.54, 30.01]",35.44,28.95

# PCSM TRAIN AND STORE THE BEST MODEL

In [15]:
doc1_df_train = pd.read_csv("/content/drive/MyDrive/Memoire/DIORES/Datasets/V2/L1PCSM/doc1/doc1_df_train.csv");
doc2_df_train = pd.read_csv("/content/drive/MyDrive/Memoire/DIORES/Datasets/V2/L1PCSM/doc2/doc2_df_train.csv");
doc3_df_train = pd.read_csv("/content/drive/MyDrive/Memoire/DIORES/Datasets/V2/L1PCSM/doc3/doc3_df_train.csv");

In [16]:
# Préparer les données
train_dfs = [doc1_df_train, doc2_df_train, doc3_df_train]
names = ['Doc1', 'Doc2', 'Doc3']

# Entraîner les modèles
best_models = train_lasso_models(
    train_dfs=train_dfs,  # Liste des DataFrames d'entraînement
    res=res,             # Combinaisons de features à tester
    names=names,         # Noms des documents
    target_col='Score L1', # Variable cible
    alpha=0.01           # Paramètre de régularisation
)


# Sauvegarder les modèles
save_models(
    final_results=best_models,
    base_path='models'  # Dossier de sauvegarde
)

# print("Best Model : ", best_models)


# Reformater les données
data = []
for doc, values in best_models.items():
    data.append({
        'Document': doc,
        'Features': ', '.join(values['features']),
        # 'Modèle': str(values['model']),
        # 'Scaler': str(values['scaler']),
        'coefs': [round(float(c), 2) for c in values['coefs']],
        'RMSE Validation': round(float(values['val_rmse']), 2),
        'MAE Validation': round(float(values['val_mae']), 2)
    })

# Créer un DataFrame
df_best_models = pd.DataFrame(data)

# Afficher joliment
print(df_best_models.to_string(index=False))

Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
               Feature  Coefficient
4  Moy. sur Mat.Fond.     3.436728
3                  AN     2.593365
0                 SVT     0.916770
1                  FR     0.389221
2               PHILO     0.000000
5                  S2     0.000000
RMSE : 33.82409202585069
MAE : 19.555356247720745
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4  Moy. sur Mat.Fond.     3.190951
3                  AN     2.577091
5      Academie perf.     1.634633
0                 SVT     0.948628
1                  FR     0.252187
2               PHILO     0.000000
RMSE : 34.05267173887877
MAE : 19.493681412144014
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4  Moy. sur Mat.Fond.     3.436728
3                  AN     2.593365
0                 SVT     0.916770
1                  FR     0.389221
2               PHILO     0.000000
5     Residence perf.     0.000000
RMSE : 33.82409202585069
MAE : 19.555356247720745
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5                    S1     1.671748
3                    AN     1.372433
0                   SVT     0.706328
1                    FR     0.000000
2                 PHILO     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 34.07784390155754
MAE : 19.21247925343188
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
3                    AN     1.523440
0                   SVT     0.804635
1                    FR     0.000000
2                 PHILO     0.000000
4  Age en Décembre 2018     0.000000
5                    S2     0.000000
RMSE : 34.09414273927662
MAE : 19.32512394050584
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5        Academie perf.     1.986635
3                    AN     1.574707
0                   SVT     0.836762
1                    FR     0.000000
2                 PHILO     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 34.348982180483596
MAE : 19.187411583813464
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
3                    AN     1.506364
0                   SVT     0.831989
5       Residence perf.     0.529630
1                    FR     0.000000
2                 PHILO     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 34.06650774747446
MAE : 19.310211274351953
 ______________________________
Coefficients LASSO :
   Feature  Coefficient
4      S1     1.671748
3      AN     1.372433
0     SVT     0.706328
1      FR     0.000000
2   PHILO     0.000000
5      S2     0.000000
RMSE : 34.07784390155754
MAE : 19.21247925343188
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
5  Academie perf.     1.994093
4              S1     1.680694
3              AN     1.423085
0             SVT     0.738049
1              FR     0.000000
2           PHILO     0.000000
RMSE : 34.335721679906314
MAE : 19.07364710549644
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
4               S1     1.707819
3               AN     1.348958
0              SVT     0.736593
5  Residence perf.     0.627081
1               FR     0.000000
2            PHILO     0.000000
RMSE : 34.046442161110434
MAE : 19.192392400521022
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
5  Academie perf.     1.986635
3              AN     1.574707
0             SVT     0.836762
1              FR     0.000000
2           PHILO     0.000000
4              S2     0.000000
RMSE : 34.348982180483596
MAE : 19.187411583813464
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
3               AN     1.506364
0              SVT     0.831989
5  Residence perf.     0.529630
1               FR     0.000000
2            PHILO     0.000000
4               S2     0.000000
RMSE : 34.06650774747446
MAE : 19.310211274351953
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
4   Academie perf.     1.986635
3               AN     1.574707
0              SVT     0.836762
1               FR     0.000000
2            PHILO     0.000000
5  Residence perf.     0.000000
RMSE : 34.348982180483596
MAE : 19.187411583813464
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
4    Moy. sur Mat.Fond.     2.628531
0                   SVT     0.872867
1                    FR     0.524896
2                 PHILO     0.000000
3              Moy. Gle     0.000000
5  Age en Décembre 2018     0.000000
RMSE : 33.69669088258895
MAE : 19.152343972047003
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4  Moy. sur Mat.Fond.     2.705852
5                  S1     1.906985
0                 SVT     0.767557
1                  FR     0.493442
3            Moy. Gle     0.000000
2               PHILO     0.000000
RMSE : 33.69426023396341
MAE : 19.055986427259725
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4  Moy. sur Mat.Fond.     2.628531
0                 SVT     0.872867
1                  FR     0.524896
2               PHILO     0.000000
3            Moy. Gle     0.000000
5                  S2     0.000000
RMSE : 33.69669088258895
MAE : 19.152343972047003
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4  Moy. sur Mat.Fond.     2.384415
5      Academie perf.     1.657877
0                 SVT     0.905425
1                  FR     0.385091
3            Moy. Gle     0.000000
2               PHILO     0.000000
RMSE : 33.940094505967465
MAE : 19.097621861131742
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4  Moy. sur Mat.Fond.     2.628531
0                 SVT     0.872867
1                  FR     0.524896
2               PHILO     0.000000
3            Moy. Gle     0.000000
5     Residence perf.     0.000000
RMSE : 33.69669088258895
MAE : 19.152343972047003
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5                    S1     1.795993
3              Moy. Gle     0.822186
0                   SVT     0.791107
1                    FR     0.000000
2                 PHILO     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 33.89479171802019
MAE : 19.042610182515787
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
0                   SVT     0.897486
3              Moy. Gle     0.822535
1                    FR     0.000000
2                 PHILO     0.000000
4  Age en Décembre 2018     0.000000
5                    S2     0.000000
RMSE : 33.89510646748647
MAE : 19.141544432085425
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5        Academie perf.     1.866020
0                   SVT     0.899025
3              Moy. Gle     0.546585
1                    FR     0.000000
2                 PHILO     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 34.16234994433394
MAE : 19.00492873049851
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
0                   SVT     0.899659
3              Moy. Gle     0.702540
5       Residence perf.     0.285799
1                    FR     0.000000
2                 PHILO     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 33.894381472242756
MAE : 19.13126812439837
 ______________________________
Coefficients LASSO :
     Feature  Coefficient
4        S1     1.795993
3  Moy. Gle     0.822186
0       SVT     0.791107
1        FR     0.000000
2     PHILO     0.000000
5        S2     0.000000
RMSE : 33.89479171802019
MAE : 19.042610182515787
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
5  Academie perf.     1.878583
4              S1     1.808799
0             SVT     0.791898
3        Moy. Gle     0.544376
1              FR     0.000000
2           PHILO     0.000000
RMSE : 34.16566455229515
MAE : 18.905849010084165
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
4               S1     1.817950
0              SVT     0.792900
3         Moy. Gle     0.652111
5  Residence perf.     0.405116
1               FR     0.000000
2            PHILO     0.000000
RMSE : 33.894656135042794
MAE : 19.02683549193751
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
5  Academie perf.     1.866020
0             SVT     0.899025
3        Moy. Gle     0.546585
1              FR     0.000000
2           PHILO     0.000000
4              S2     0.000000
RMSE : 34.16234994433394
MAE : 19.00492873049851
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
0              SVT     0.899659
3         Moy. Gle     0.702540
5  Residence perf.     0.285799
1               FR     0.000000
2            PHILO     0.000000
4               S2     0.000000
RMSE : 33.894381472242756
MAE : 19.13126812439837
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
4   Academie perf.     1.866020
0              SVT     0.899025
3         Moy. Gle     0.546585
1               FR     0.000000
2            PHILO     0.000000
5  Residence perf.     0.000000
RMSE : 34.16234994433394
MAE : 19.00492873049851
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
3    Moy. sur Mat.Fond.     2.705843
5                    S1     1.906985
0                   SVT     0.767575
1                    FR     0.493418
2                 PHILO     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 33.69426428353674
MAE : 19.055990871082003
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
3    Moy. sur Mat.Fond.     2.628526
0                   SVT     0.872878
1                    FR     0.524882
2                 PHILO     0.000000
4  Age en Décembre 2018     0.000000
5                    S2     0.000000
RMSE : 33.6966932731934
MAE : 19.152346549569792
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
3    Moy. sur Mat.Fond.     2.384427
5        Academie perf.     1.657874
0                   SVT     0.905407
1                    FR     0.385120
2                 PHILO     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 33.94008957829592
MAE : 19.09761668896536
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
3    Moy. sur Mat.Fond.     2.628526
0                   SVT     0.872878
1                    FR     0.524882
2                 PHILO     0.000000
4  Age en Décembre 2018     0.000000
5       Residence perf.     0.000000
RMSE : 33.6966932731934
MAE : 19.152346549569792
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
3  Moy. sur Mat.Fond.     2.705843
4                  S1     1.906985
0                 SVT     0.767575
1                  FR     0.493418
2               PHILO     0.000000
5                  S2     0.000000
RMSE : 33.69426428353674
MAE : 19.055990871082003
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
3  Moy. sur Mat.Fond.     2.461183
4                  S1     1.911234
5      Academie perf.     1.662828
0                 SVT     0.799971
1                  FR     0.353159
2               PHILO     0.000000
RMSE : 33.9396803476694
MAE : 19.008805851026775
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
3  Moy. sur Mat.Fond.     2.705843
4                  S1     1.906985
0                 SVT     0.767575
1                  FR     0.493418
2               PHILO     0.000000
5     Residence perf.     0.000000
RMSE : 33.69426428353674
MAE : 19.055990871082003
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
3  Moy. sur Mat.Fond.     2.384427
5      Academie perf.     1.657874
0                 SVT     0.905407
1                  FR     0.385120
2               PHILO     0.000000
4                  S2     0.000000
RMSE : 33.94008957829592
MAE : 19.09761668896536
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
3  Moy. sur Mat.Fond.     2.628526
0                 SVT     0.872878
1                  FR     0.524882
2               PHILO     0.000000
4                  S2     0.000000
5     Residence perf.     0.000000
RMSE : 33.6966932731934
MAE : 19.152346549569792
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
3  Moy. sur Mat.Fond.     2.384427
4      Academie perf.     1.657874
0                 SVT     0.905407
1                  FR     0.385120
2               PHILO     0.000000
5     Residence perf.     0.000000
RMSE : 33.94008957829592
MAE : 19.09761668896536
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
4                    S1     1.796152
0                   SVT     0.705126
1                    FR     0.000000
2                 PHILO     0.000000
3  Age en Décembre 2018     0.000000
5                    S2     0.000000
RMSE : 33.97107628278083
MAE : 19.018729190757707
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5        Academie perf.     1.958231
4                    S1     1.809445
0                   SVT     0.736234
1                    FR     0.000000
3  Age en Décembre 2018     0.000000
2                 PHILO     0.000000
RMSE : 34.22777758548221
MAE : 18.880755989804165
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
4                    S1     1.832821
0                   SVT     0.737844
5       Residence perf.     0.677448
1                    FR     0.000000
3  Age en Décembre 2018     0.000000
2                 PHILO     0.000000
RMSE : 33.944194884048066
MAE : 19.000609084263104
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5        Academie perf.     1.945988
0                   SVT     0.843173
1                    FR     0.000000
2                 PHILO     0.000000
3  Age en Décembre 2018     0.000000
4                    S2     0.000000
RMSE : 34.224105592090446
MAE : 18.979976867778664
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
0                   SVT     0.841262
5       Residence perf.     0.578326
1                    FR     0.000000
2                 PHILO     0.000000
3  Age en Décembre 2018     0.000000
4                    S2     0.000000
RMSE : 33.94659401156116
MAE : 19.10391745819371
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
4        Academie perf.     1.945988
0                   SVT     0.843173
1                    FR     0.000000
2                 PHILO     0.000000
3  Age en Décembre 2018     0.000000
5       Residence perf.     0.000000
RMSE : 34.224105592090446
MAE : 18.979976867778664
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
5  Academie perf.     1.958231
3              S1     1.809445
0             SVT     0.736234
1              FR     0.000000
2           PHILO     0.000000
4              S2     0.000000
RMSE : 34.22777758548221
MAE : 18.880755989804165
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
3               S1     1.832821
0              SVT     0.737844
5  Residence perf.     0.677448
1               FR     0.000000
2            PHILO     0.000000
4               S2     0.000000
RMSE : 33.944194884048066
MAE : 19.000609084263104
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
4   Academie perf.     1.951973
3               S1     1.810411
0              SVT     0.737034
5  Residence perf.     0.018631
1               FR     0.000000
2            PHILO     0.000000
RMSE : 34.2262280618864
MAE : 18.88070953945862
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
4   Academie perf.     1.945988
0              SVT     0.843173
1               FR     0.000000
2            PHILO     0.000000
3               S2     0.000000
5  Residence perf.     0.000000
RMSE : 34.224105592090446
MAE : 18.979976867778664
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
4    Moy. sur Mat.Fond.     3.436710
2                    AN     2.593342
0                   SVT     0.916794
1                    FR     0.389190
3              Moy. Gle     0.000000
5  Age en Décembre 2018     0.000000
RMSE : 33.82409573030537
MAE : 19.555358102502435
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4  Moy. sur Mat.Fond.     3.461739
2                  AN     2.449324
5                  S1     1.724129
0                 SVT     0.819136
1                  FR     0.368298
3            Moy. Gle     0.000000
RMSE : 33.80694803450511
MAE : 19.444705496213754
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4  Moy. sur Mat.Fond.     3.436710
2                  AN     2.593342
0                 SVT     0.916794
1                  FR     0.389190
3            Moy. Gle     0.000000
5                  S2     0.000000
RMSE : 33.82409573030537
MAE : 19.555358102502435
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4  Moy. sur Mat.Fond.     3.190949
2                  AN     2.577076
5      Academie perf.     1.634632
0                 SVT     0.948624
1                  FR     0.252195
3            Moy. Gle     0.000000
RMSE : 34.05266949306231
MAE : 19.493677816496934
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4  Moy. sur Mat.Fond.     3.436710
2                  AN     2.593342
0                 SVT     0.916794
1                  FR     0.389190
3            Moy. Gle     0.000000
5     Residence perf.     0.000000
RMSE : 33.82409573030537
MAE : 19.555358102502435
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5                    S1     1.670946
2                    AN     1.379504
3              Moy. Gle     0.833915
0                   SVT     0.793542
1                    FR     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 33.99857627599134
MAE : 19.23769910856302
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                    AN     1.530451
0                   SVT     0.891970
3              Moy. Gle     0.835521
1                    FR     0.000000
4  Age en Décembre 2018     0.000000
5                    S2     0.000000
RMSE : 34.01523820972298
MAE : 19.35033825997395
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5        Academie perf.     1.905632
2                    AN     1.577267
0                   SVT     0.893372
3              Moy. Gle     0.554110
1                    FR     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 34.28499499047752
MAE : 19.20974857272122
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
2                    AN     1.522598
0                   SVT     0.893675
3              Moy. Gle     0.743254
5       Residence perf.     0.219627
1                    FR     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 34.01258896595766
MAE : 19.341370562779556
 ______________________________
Coefficients LASSO :
     Feature  Coefficient
4        S1     1.670946
2        AN     1.379504
3  Moy. Gle     0.833915
0       SVT     0.793542
1        FR     0.000000
5        S2     0.000000

# BCGS TRAIN AND STORE THE BEST MODEL

In [17]:
doc1_df_train = pd.read_csv("/content/drive/MyDrive/Memoire/DIORES/Datasets/V2/L1BCGS/doc1/doc1_df_train.csv");
doc2_df_train = pd.read_csv("/content/drive/MyDrive/Memoire/DIORES/Datasets/V2/L1BCGS/doc2/doc2_df_train.csv");
doc3_df_train = pd.read_csv("/content/drive/MyDrive/Memoire/DIORES/Datasets/V2/L1BCGS/doc3/doc3_df_train.csv");

In [18]:
# Préparer les données
train_dfs = [doc1_df_train, doc2_df_train, doc3_df_train]
names = ['Doc1', 'Doc2', 'Doc3']

# Entraîner les modèles
best_models = train_lasso_models(
    train_dfs=train_dfs,  # Liste des DataFrames d'entraînement
    res=res,             # Combinaisons de features à tester
    names=names,         # Noms des documents
    target_col='Score L1', # Variable cible
    alpha=0.01           # Paramètre de régularisation
)


# Sauvegarder les modèles
save_models(
    final_results=best_models,
    base_path='models'  # Dossier de sauvegarde
)

# print("Best Model : ", best_models)


# Reformater les données
data = []
for doc, values in best_models.items():
    data.append({
        'Document': doc,
        'Features': ', '.join(values['features']),
        # 'Modèle': str(values['model']),
        # 'Scaler': str(values['scaler']),
        'coefs': [round(float(c), 2) for c in values['coefs']],
        'RMSE Validation': round(float(values['val_rmse']), 2),
        'MAE Validation': round(float(values['val_mae']), 2)
    })

# Créer un DataFrame
df_best_models = pd.DataFrame(data)

# Afficher joliment
print(df_best_models.to_string(index=False))

Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
               Feature  Coefficient
1                  FR     1.914619
2               PHILO     1.237163
0                 SVT     0.000000
3                  AN     0.000000
4  Moy. sur Mat.Fond.     0.000000
5                  S2     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
1                  FR     1.914619
2               PHILO     1.237163
0                 SVT     0.000000
3                  AN     0.000000
4  Moy. sur Mat.Fond.     0.000000
5      Academie perf.     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
1                  FR     1.883051
2               PHILO     1.200935
5     Residence perf.     0.522900
0                 SVT     0.000000
3                  AN     0.000000
4  Moy. sur Mat.Fond.     0.000000
RMSE : 39.77484735696042
MAE : 32.96037203658465
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5                    S1     3.467462
1                    FR     1.634500
2                 PHILO     1.304011
0                   SVT     0.000000
3                    AN     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 39.74057776837833
MAE : 32.891568199429216
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     1.914619
2                 PHILO     1.237163
0                   SVT     0.000000
3                    AN     0.000000
4  Age en Décembre 2018     0.000000
5                    S2     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     1.914619
2                 PHILO     1.237163
0                   SVT     0.000000
3                    AN     0.000000
4  Age en Décembre 2018     0.000000
5        Academie perf.     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     1.883051
2                 PHILO     1.200935
5       Residence perf.     0.522900
0                   SVT     0.000000
3                    AN     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 39.77484735696042
MAE : 32.96037203658465
 ______________________________
Coefficients LASSO :
   Feature  Coefficient
4      S1     3.467462
1      FR     1.634500
2   PHILO     1.304011
0     SVT     0.000000
3      AN     0.000000
5      S2     0.000000
RMSE : 39.74057776837833
MAE : 32.891568199429216
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
4              S1     3.467462
1              FR     1.634500
2           PHILO     1.304011
0             SVT     0.000000
3              AN     0.000000
5  Academie perf.     0.000000
RMSE : 39.74057776837833
MAE : 32.891568199429216
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
4               S1     3.476757
1               FR     1.598807
2            PHILO     1.264082
5  Residence perf.     0.578925
0              SVT     0.000000
3               AN     0.000000
RMSE : 39.763714728353186
MAE : 32.87571750294201
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
1              FR     1.914619
2           PHILO     1.237163
0             SVT     0.000000
3              AN     0.000000
4              S2     0.000000
5  Academie perf.     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
1               FR     1.883051
2            PHILO     1.200935
5  Residence perf.     0.522900
0              SVT     0.000000
3               AN     0.000000
4               S2     0.000000
RMSE : 39.77484735696042
MAE : 32.96037203658465
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
1               FR     1.883051
2            PHILO     1.200935
5  Residence perf.     0.522900
0              SVT     0.000000
3               AN     0.000000
4   Academie perf.     0.000000
RMSE : 39.77484735696042
MAE : 32.96037203658465
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     1.914619
2                 PHILO     1.237163
0                   SVT     0.000000
3              Moy. Gle     0.000000
4    Moy. sur Mat.Fond.     0.000000
5  Age en Décembre 2018     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
5                  S1     3.467462
1                  FR     1.634500
2               PHILO     1.304011
0                 SVT     0.000000
3            Moy. Gle     0.000000
4  Moy. sur Mat.Fond.     0.000000
RMSE : 39.74057776837833
MAE : 32.891568199429216
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
1                  FR     1.914619
2               PHILO     1.237163
0                 SVT     0.000000
3            Moy. Gle     0.000000
4  Moy. sur Mat.Fond.     0.000000
5                  S2     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
1                  FR     1.914619
2               PHILO     1.237163
0                 SVT     0.000000
3            Moy. Gle     0.000000
4  Moy. sur Mat.Fond.     0.000000
5      Academie perf.     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
1                  FR     1.883051
2               PHILO     1.200935
5     Residence perf.     0.522900
0                 SVT     0.000000
3            Moy. Gle     0.000000
4  Moy. sur Mat.Fond.     0.000000
RMSE : 39.77484735696042
MAE : 32.96037203658465
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5                    S1     3.467462
1                    FR     1.634500
2                 PHILO     1.304011
0                   SVT     0.000000
3              Moy. Gle     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 39.74057776837833
MAE : 32.891568199429216
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     1.914619
2                 PHILO     1.237163
0                   SVT     0.000000
3              Moy. Gle     0.000000
4  Age en Décembre 2018     0.000000
5                    S2     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     1.914619
2                 PHILO     1.237163
0                   SVT     0.000000
3              Moy. Gle     0.000000
4  Age en Décembre 2018     0.000000
5        Academie perf.     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     1.883051
2                 PHILO     1.200935
5       Residence perf.     0.522900
0                   SVT     0.000000
3              Moy. Gle     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 39.77484735696042
MAE : 32.96037203658465
 ______________________________
Coefficients LASSO :
     Feature  Coefficient
4        S1     3.467462
1        FR     1.634500
2     PHILO     1.304011
0       SVT     0.000000
3  Moy. Gle     0.000000
5        S2     0.000000
RMSE : 39.74057776837833
MAE : 32.891568199429216
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
4              S1     3.467462
1              FR     1.634500
2           PHILO     1.304011
0             SVT     0.000000
3        Moy. Gle     0.000000
5  Academie perf.     0.000000
RMSE : 39.74057776837833
MAE : 32.891568199429216
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
4               S1     3.476757
1               FR     1.598807
2            PHILO     1.264082
5  Residence perf.     0.578925
0              SVT     0.000000
3         Moy. Gle     0.000000
RMSE : 39.763714728353186
MAE : 32.87571750294201
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
1              FR     1.914619
2           PHILO     1.237163
0             SVT     0.000000
3        Moy. Gle     0.000000
4              S2     0.000000
5  Academie perf.     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
1               FR     1.883051
2            PHILO     1.200935
5  Residence perf.     0.522900
0              SVT     0.000000
3         Moy. Gle     0.000000
4               S2     0.000000
RMSE : 39.77484735696042
MAE : 32.96037203658465
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
1               FR     1.883051
2            PHILO     1.200935
5  Residence perf.     0.522900
0              SVT     0.000000
3         Moy. Gle     0.000000
4   Academie perf.     0.000000
RMSE : 39.77484735696042
MAE : 32.96037203658465
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5                    S1     3.467462
1                    FR     1.634500
2                 PHILO     1.304011
0                   SVT     0.000000
3    Moy. sur Mat.Fond.     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 39.74057776837833
MAE : 32.891568199429216
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     1.914619
2                 PHILO     1.237163
0                   SVT     0.000000
3    Moy. sur Mat.Fond.     0.000000
4  Age en Décembre 2018     0.000000
5                    S2     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     1.914619
2                 PHILO     1.237163
0                   SVT     0.000000
3    Moy. sur Mat.Fond.     0.000000
4  Age en Décembre 2018     0.000000
5        Academie perf.     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     1.883051
2                 PHILO     1.200935
5       Residence perf.     0.522900
0                   SVT     0.000000
3    Moy. sur Mat.Fond.     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 39.77484735696042
MAE : 32.96037203658465
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4                  S1     3.467462
1                  FR     1.634500
2               PHILO     1.304011
0                 SVT     0.000000
3  Moy. sur Mat.Fond.     0.000000
5                  S2     0.000000
RMSE : 39.74057776837833
MAE : 32.891568199429216
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4                  S1     3.467462
1                  FR     1.634500
2               PHILO     1.304011
0                 SVT     0.000000
3  Moy. sur Mat.Fond.     0.000000
5      Academie perf.     0.000000
RMSE : 39.74057776837833
MAE : 32.891568199429216
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
4                  S1     3.476757
1                  FR     1.598807
2               PHILO     1.264082
5     Residence perf.     0.578925
0                 SVT     0.000000
3  Moy. sur Mat.Fond.     0.000000
RMSE : 39.763714728353186
MAE : 32.87571750294201
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
1                  FR     1.914619
2               PHILO     1.237163
0                 SVT     0.000000
3  Moy. sur Mat.Fond.     0.000000
4                  S2     0.000000
5      Academie perf.     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
1                  FR     1.883051
2               PHILO     1.200935
5     Residence perf.     0.522900
0                 SVT     0.000000
3  Moy. sur Mat.Fond.     0.000000
4                  S2     0.000000
RMSE : 39.77484735696042
MAE : 32.96037203658465
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
1                  FR     1.883051
2               PHILO     1.200935
5     Residence perf.     0.522900
0                 SVT     0.000000
3  Moy. sur Mat.Fond.     0.000000
4      Academie perf.     0.000000
RMSE : 39.77484735696042
MAE : 32.96037203658465
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
4                    S1     3.467462
1                    FR     1.634500
2                 PHILO     1.304011
0                   SVT     0.000000
3  Age en Décembre 2018     0.000000
5                    S2     0.000000
RMSE : 39.74057776837833
MAE : 32.891568199429216
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
4                    S1     3.467462
1                    FR     1.634500
2                 PHILO     1.304011
0                   SVT     0.000000
3  Age en Décembre 2018     0.000000
5        Academie perf.     0.000000
RMSE : 39.74057776837833
MAE : 32.891568199429216
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
4                    S1     3.476757
1                    FR     1.598807
2                 PHILO     1.264082
5       Residence perf.     0.578925
0                   SVT     0.000000
3  Age en Décembre 2018     0.000000
RMSE : 39.763714728353186
MAE : 32.87571750294201
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     1.914619
2                 PHILO     1.237163
0                   SVT     0.000000
3  Age en Décembre 2018     0.000000
4                    S2     0.000000
5        Academie perf.     0.000000
RMSE : 39.75436549770721
MAE : 32.97448748336353
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     1.883051
2                 PHILO     1.200935
5       Residence perf.     0.522900
0                   SVT     0.000000
3  Age en Décembre 2018     0.000000
4                    S2     0.000000
RMSE : 39.77484735696042
MAE : 32.96037203658465
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     1.883051
2                 PHILO     1.200935
5       Residence perf.     0.522900
0                   SVT     0.000000
3  Age en Décembre 2018     0.000000
4        Academie perf.     0.000000
RMSE : 39.77484735696042
MAE : 32.96037203658465
 ______________________________
Coefficients LASSO :
           Feature  Coefficient
3              S1     3.467462
1              FR     1.634500
2           PHILO     1.304011
0             SVT     0.000000
4              S2     0.000000
5  Academie perf.     0.000000
RMSE : 39.74057776837833
MAE : 32.891568199429216
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
3               S1     3.476757
1               FR     1.598807
2            PHILO     1.264082
5  Residence perf.     0.578925
0              SVT     0.000000
4               S2     0.000000
RMSE : 39.763714728353186
MAE : 32.87571750294201
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
3               S1     3.476757
1               FR     1.598807
2            PHILO     1.264082
5  Residence perf.     0.578925
0              SVT     0.000000
4   Academie perf.     0.000000
RMSE : 39.763714728353186
MAE : 32.87571750294201
 ______________________________
Coefficients LASSO :
            Feature  Coefficient
1               FR     1.883051
2            PHILO     1.200935
5  Residence perf.     0.522900
0              SVT     0.000000
3               S2     0.000000
4   Academie perf.     0.000000
RMSE : 39.77484735696042
MAE : 32.96037203658465
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     2.132191
0                   SVT     0.000000
2                    AN     0.000000
3              Moy. Gle     0.000000
4    Moy. sur Mat.Fond.     0.000000
5  Age en Décembre 2018     0.000000
RMSE : 39.80618375399779
MAE : 33.00049561443164
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
5                  S1     3.442953
1                  FR     1.865724
0                 SVT     0.000000
2                  AN     0.000000
3            Moy. Gle     0.000000
4  Moy. sur Mat.Fond.     0.000000
RMSE : 39.794339708145955
MAE : 32.91955785762361
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
1                  FR     2.132191
0                 SVT     0.000000
2                  AN     0.000000
3            Moy. Gle     0.000000
4  Moy. sur Mat.Fond.     0.000000
5                  S2     0.000000
RMSE : 39.80618375399779
MAE : 33.00049561443164
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
1                  FR     2.132191
0                 SVT     0.000000
2                  AN     0.000000
3            Moy. Gle     0.000000
4  Moy. sur Mat.Fond.     0.000000
5      Academie perf.     0.000000
RMSE : 39.80618375399779
MAE : 33.00049561443164
 ______________________________
Coefficients LASSO :
               Feature  Coefficient
1                  FR     2.088381
5     Residence perf.     0.603959
0                 SVT     0.000000
2                  AN     0.000000
3            Moy. Gle     0.000000
4  Moy. sur Mat.Fond.     0.000000
RMSE : 39.828206587566434
MAE : 32.98331167289989
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
5                    S1     3.442953
1                    FR     1.865724
0                   SVT     0.000000
2                    AN     0.000000
3              Moy. Gle     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 39.794339708145955
MAE : 32.91955785762361
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     2.132191
0                   SVT     0.000000
2                    AN     0.000000
3              Moy. Gle     0.000000
4  Age en Décembre 2018     0.000000
5                    S2     0.000000
RMSE : 39.80618375399779
MAE : 33.00049561443164
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     2.132191
0                   SVT     0.000000
2                    AN     0.000000
3              Moy. Gle     0.000000
4  Age en Décembre 2018     0.000000
5        Academie perf.     0.000000
RMSE : 39.80618375399779
MAE : 33.00049561443164
 ______________________________
Coefficients LASSO :
                 Feature  Coefficient
1                    FR     2.088381
5       Residence perf.     0.603959
0                   SVT     0.000000
2                    AN     0.000000
3              Moy. Gle     0.000000
4  Age en Décembre 2018     0.000000
RMSE : 39.828206587566434
MAE : 32.98331167289989
 ______________________________
Coefficients LASSO :
     Feature  Coefficient
4        S1     3.442953
1        FR     1.865724
0       SVT     0.000000
2        AN     0.000000
3  Moy. Gle     0.000000
5        S2     0.000000
RMSE : 39.794339708145955